# Generated by Django 5.1.6 on 2025-02-22 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_respond_options_alter_respond_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respond',
            options={'verbose_name': 'Отклик', 'verbose_name_plural': 'Отклики'},
        ),
    ]
